name: Complete python Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        default: '3.9'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      registry:
        description: 'Docker registry to push the image (e.g., ghcr.io/org/app)'
        required: false
        default: 'ghcr.io'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: "pylint $(git ls-files '*.py')"
        type: string

      test-command:
        description: 'test command (e.g., npm test)'
        required: false
        default: 'python -m unittest discover tests'
        type: string
        
      package-command:
        description: "Command to package the app"
        required: false
        default: 'python -m build'
        type: string

      package-output:
        description: "Directory or file path to upload as package artifact"
        required: false
        default: 'dist/'
        type: string

      artifact-name:
        description: "Name of the uploaded artifact"
        required: false
        default: 'python-package'
        type: string

      conventional-commit:
        description: 'Use conventional commit messages to determine the version bump'
        required: false
        default: 'false'
        type: string
      
      run_trivy:
        description: 'Run Trivy Scan'
        required: false
        default: 'true'
        type: string

      run_grype:
        description: 'Run Grype Scan'
        required: false
        default: 'true'
        type: string

      continue-on-error:
        description: "Continue on error for linting"
        required: false
        default: 'true'
        type: string

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write

jobs:
  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
    # This job sets up Node.js and runs the lint command
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/python/setup@main
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      # This job sets up Node.js and runs the lint command
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/python/lint@main
        with:
          lint-command: ${{ inputs.lint-command }}
          continue-on-error: ${{ inputs.continue-on-error }}
          working-directory: ${{ inputs.working-directory }}
      

      # This job summarizes the build report and writes it to GITHUB_STEP_SUMMARY
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/github-actions/git-dashboard@main
        with:
          tool: PyLint
          title: Lint Report (Text)
          report: pylint-report.txt
          max-lines: 100
          # thresholds: "Code Quality|<|5.0"

  # This job executes unit test
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # This job sets up Python and runs unit tests
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/python/setup@main
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      # This step runs the unit tests using Jest
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/python/unittest@main
        with:
          test-command: ${{ inputs.test-command }}
          continue-on-error: ${{ inputs.continue-on-error }}
      
      # This job summarizes the Jest report and writes it to GITHUB_STEP_SUMMARY
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/github-actions/git-dashboard@main
        with:
          tool: Unit Test
          title: Unit Test Results
          report: unittest-report.txt
          fail-on-keywords: 'fail,error,exception'
          max-lines: 100

  
  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  security-scan:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      # This job sets up Python environment
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/python/setup@main
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/static-code-analysis/codeql@main
        with:
          languages: python
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.continue-on-error }}
      
      # This job summarizes the CodeQL report and writes it to GITHUB_STEP_SUMMARY
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/github-actions/git-dashboard@main
        with:
          tool: CodeQL
          title: Security Issues
          report: codeql-results.sarif
          format: sarif
          max-lines: 100

  # This job builds the Python package
  version:
    runs-on: ubuntu-latest
    needs: [build, unit-test]
    outputs:
      tag: ${{ steps.set-output.outputs.tag }}
    steps:
      # This job generates a semantic version tag based on the commit history
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/github-actions/git-tag-generation@main
        id: set-output
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          conventional-commit: 'false'  # Set to 'true' if you want to use conventional commits for tagging

  # This job publishes the Docker image to GitHub Container Registry (GHCR) if a new tag is generated
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [version, build, unit-test]
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
    steps:
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/docker-build-push@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.registry }}
          version: ${{ needs.version.outputs.tag }}

  # This job scans the Docker image for vulnerabilities using Trivy and Grype
  docker-scan:
    runs-on: ubuntu-latest
    needs: [version, docker-build-and-push]
    if: ${{ needs.version.outputs.tag != '' }}
    permissions:
      contents: read
      packages: read 
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/security-scanner/trivy-scan@main
        if: ${{ inputs.run_trivy == 'true' }}
        with:
          version: ${{ needs.version.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'

      # This job summarizes the Trivy report and writes it to GITHUB_STEP_SUMMARY
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/github-actions/git-dashboard@main
        if: ${{ inputs.run_trivy == 'true' }}
        with:
          tool: Trivy
          title: Trivy Vulnerability Report
          report: trivy-report.txt
          format: text
          max-lines: 100

      # This job scans the Docker image for vulnerabilities using Grype
      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/security-scanner/grype-scan@main
        if: ${{ inputs.run_grype == 'true' }}
        with:
          version: ${{ needs.version.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # This job summarizes the Grype report and writes it to GITHUB_STEP_SUMMARY

      - uses: KaranbirSinghAhluwalia/Github-actions/.github/actions/common/github-actions/git-dashboard@main
        if: ${{ inputs.run_grype == 'true' }}
        with:
          tool: Grype
          title: Grype Vulnerability Report
          report: grype-report.txt
          max-lines: 100

